#!/command/with-contenv bash

if [ ! -d /var/log/apache2 ]; then
    mkdir -p /var/log/apache2
    ln -sf /proc/1/fd/1 /var/log/apache2/access.log
    ln -sf /proc/1/fd/1 /var/log/apache2/other_vhosts_access.log
    ln -sf /proc/1/fd/2 /var/log/apache2/error.log
fi

echo
/usr/sbin/apache2ctl -v
/usr/sbin/apache2ctl configtest

echo
